name: Run Formatting Check

on:
  pull_request:
    branches: main

jobs:
  formatting_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run prettier-check
